# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Comparacion entre maximos y minimos en Matrices cuadradas
#'@description Compara la primera fila de la primera matriz con la columna de la 
#'segunda matriz tomando los valores minimos entre ambos y generando un nuevo vector
#'luego dentro de ese vector ver cual es el maximo, lo que nos lleva al valor que queda
#'en esa posicion
#'@param NumericMatrix A : Matriz cuadrada de NxN
#'@param NumericMatrix B : Matriz cuadrada de NxN
#'@return Devuelve una matriz de NxN con los valores resultantes de dicha comparacion
#'realizada dentro de la funcion.
#'@example
#'
#'matrizPrueba1 <- matrix(round(runif(16, 1, 10)), nrow = 4, ncol = 4)
#'matrizPrueba2 <- matrix(round(runif(16, 10, 20)), nrow = 4, ncol = 4)
#'set.seed(123)
#'  
#'matrizPrueba1
#'matrizPrueba2
#'
#'MAX_MIN_rcpp(matrizPrueba1, matrizPrueba2)
#'´
#'
NULL

MAX_MIN_rcpp <- function(A, B) {
    .Call(`_NRCPP_MAX_MIN_rcpp`, A, B)
}

#'@title Combinar Objetos R por Columnas
#'@description Funcion que realiza la union de un DataFrame o Matriz con un vector.
#'@param RObjeto A : Objeto que puede ser un DataFrame o Matriz.
#'@param NumericVector x : Objeto de tipo vector numerico que debe ser del mismo tamaño 
#'que las columnas del DataFrame o Matriz.
#'@return Devuelve una Matriz con el vector añadido como nueva columna en caso que se le pase una matriz como
#'parametro y un DataFrame con el vector como nueva columna en caso que se le pase un
#'DataFrame como parametro.
#'@example
#'matrizPrueba1 <- matrix(round(runif(16, 1, 10)), nrow = 4, ncol = 4)
#'set.seed(123)
#'matrizPrueba1
#'
#'mi_df <- data.frame(1:4, 5:8, 9:12, 13:16)
#'mi_df
#'
#'cBIND_rcpp(mi_df, x)
#'cBIND_rcpp(matrizPrueba1, x)
NULL

cBIND_rcpp <- function(A, vect) {
    .Call(`_NRCPP_cBIND_rcpp`, A, vect)
}

#'@title Multiplicacion de Objetos R de tipo Matriz
#'@description La funcion realiza la multiplicacion de dos matrices 
#'mediante su formulacion matematica de multiplicacion de matrices, lo que 
#'quiere decir que es necesario que el numero de filas de la primera matriz
#'sea igual al numero de columnas de la segunda matriz
#'@param NumericMatrix A : Matriz de dimension NxM
#'@param NumericMatrix B : MAtriz de dimension MxN
#'@return Devuelve una matriz de resultado de dimension N filas de primera 
#'matriz y N columnas de segunda matriz.
#'@example
#'
#'matrizPrueba1 <- matrix(round(runif(16, 1, 10)), nrow = 4, ncol = 4)
#'matrizPrueba2 <- matrix(round(runif(16, 10, 20)), nrow = 4, ncol = 4)
#'set.seed(123)
#'
#'matrizPrueba1
#'matrizPrueba2
#'
#'multiMATRIZ_rcpp(matrizPrueba1, matrizPrueba2)
#'
#'
NULL

multiMATRIZ_rcpp <- function(A, B) {
    .Call(`_NRCPP_multiMATRIZ_rcpp`, A, B)
}

#'@title Combinar Objetos R por filas 
#'@description Funcion que realiza la union de un DataFrame o Matriz con un vector.
#'@param RObjeto A : Objeto que puede ser un DataFrame o Matriz.
#'@param NumericVector x : Objeto de tipo vector numerico que debe ser del mismo tamaño 
#'que las columnas del DataFrame o Matriz.
#'@return Devuelve una Matriz con el vector añadido como nueva Fila en caso que se le pase una matriz como
#'parametro y un DataFrame con el vector como nueva Fila en caso que se le pase un
#'DataFrame como parametro.
#'@example
#'matrizPrueba1 <- matrix(round(runif(16, 1, 10)), nrow = 4, ncol = 4)
#'set.seed(123)
#'matrizPrueba1
#'
#'mi_df <- data.frame(1:4, 5:8, 9:12, 13:16)
#'mi_df
#'
#'rBIND_rcpp(mi_df, x)
#'rBIND_rcpp(matrizPrueba1, x)
#'
NULL

rBIND_rcpp <- function(A, vect) {
    .Call(`_NRCPP_rBIND_rcpp`, A, vect)
}

#'@title Buscardor de indices de maximos en Objetos de R
#'@description Funcion que realiza la busqueda de el o los maximos dentro de 
#'un objeto de R.
#'@param RObjeto A : Objeto R para la realizacion de la busqueda de indice de maximo.
#'@return Devuelve un DataFrame conteniendo en sus columnas las posiciones en las que
#'se encuentran el o los valores maximos dentro del objeto. 
#'@example
#'matrizPrueba1 <- matrix(round(runif(16, 1, 10)), nrow = 4, ncol = 4)
#'set.seed(123)
#'matrizPrueba1
#'
#'whichMAX_rcpp(matrizPrueba1)
#'
NULL

whichMAX_rcpp <- function(x) {
    .Call(`_NRCPP_whichMAX_rcpp`, x)
}

#'@title Buscardor de indices de maximos en Objetos de R
#'@description Funcion que realiza la busqueda de el o los minimos dentro de 
#'un objeto de R.
#'@param RObjeto A : Objeto R para la realizacion de la busqueda de indice de minimo.
#'@return Devuelve un DataFrame conteniendo en sus columnas las posiciones en las que
#'se encuentran el o los valores minimos dentro del objeto. 
#'@example
#'matrizPrueba1 <- matrix(round(runif(16, 1, 10)), nrow = 4, ncol = 4)
#'set.seed(123)
#'matrizPrueba1
#'
#'whichMIN_rcpp(matrizPrueba1)
#'
NULL

whichMIN_rcpp <- function(x) {
    .Call(`_NRCPP_whichMIN_rcpp`, x)
}

